### ISSUE TITLE
Transitions to FLUX store in components

### ISSUE THREAD

**Issue by 0xinterface** [briansostudio/teamform#77]
This is an announcement for coming changes to all of your implemented vue components, please be aware while the integration is happening, you should be finalizing your data structure in the state tree of the vuex store. this changes will happen very soon and all of the existing feature branches that implements component will be merged into feature/flux branch.

If you have any doubts while this transition take place, please free feel to reply to the comments
@BrianSo @Ag47 @clementf2b @ttchiuaa @clementf2b @singspiel @leolo322

**Comment by BrianSo** [comment]
Why merging into feature/flux? If everything merged into flux branch, this is just making another centralized branch like master, develop.

We can merge into develop and you update the changes from develop.

I suggest the changes on flux should be merged into develop soon unless they are still unstable. Also, you should split your works into branch like flux-event, flux-member instead of one big feature flux.
